version: '3.3'

services:
    jupyter:
        image: 'jupyter/datascience-notebook:latest'
        ports: 
            - '8888:8888'
        volumes: 
        - jupyter_datascientist: /home/jovyan/work
        container_name: jupyter
        environment: 
            JUPYTER_ENABLE_LAB: 'yes'

volumes: 
    jupyter_datascientist:
                

    apache:
        image: 'bitnami/apache:latest'
        ports: 
            - '80:8081'
            - '443:8443'
        volumes: 
            - /path/to/app:/app
