#Apache
FROM bitnami/minideb:stretch
LABEL maintainer "Bitnami <containers@bitnami.com>"

ENV HOME="/" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-9" \
    OS_NAME="linux"
WORKDIR /app

# Anaconda / Jupyter
FROM contimuumio/miniconda3:4.3.26
ENV ACCEPT_INTEL_PYTHON_EULA=yes
WORKDIR /home/notebooks

# Jupyter
RUN jupyter notebook --generate-config --allow-root
